const apiTypes = (key) => {
  return {
    PENDING: `${key}`,
    SUCCESS: `${key}_SUCCESS`,
    FAIL: `${key}_FAIL`
  }
}

export const INIT_PAGES = apiTypes('INIT_PAGES');
//LOGIN
export const LOGIN = apiTypes('LOGIN');
export const LOGOUT = apiTypes('LOGOUT');
export const CLEAR_CACHE_LOGIN = 'CLEAR_CACHE_LOGIN';

//SIGN UP
export const SIGN_UP_FOR_PESONAL = apiTypes('SIGN_UP_FOR_PESONAL');
export const SIGN_UP_FOR_COMPANY = apiTypes('SIGN_UP_FOR_COMPANY');

//CURRENT USER LOGGED
export const UPDATE_INFO = apiTypes('UPDATE_INFO');
export const UPDATE_PASSWORD = apiTypes('UPDATE_PASSWORD');
export const UPDATE_AVATAR = apiTypes('UPDATE_AVATAR');

//USERS MANAGEMENT
export const GET_ALL_USERS = apiTypes('GET_ALL_USERS');
export const CREATE_NEW_USER = apiTypes('CREATE_NEW_USER');
export const DELETE_USER = apiTypes('DELETE_USER');
export const GET_USER_BY_ID = apiTypes('GET_USER_BY_ID');
export const EDIT_USER_INFO = apiTypes('EDIT_USER_INFO');
export const TOGGLE_ACTIVE_USER_STATUS = apiTypes('TOGGLE_ACTIVE_USER_STATUS');

//EXAM-QUESTIONS MANAGEMENT
export const GET_ALL_EXAM_QUESTIONS = apiTypes('GET_ALL_EXAM_QUESTIONS');
export const GET_EXAM_QUESTION_BY_ID = apiTypes('GET_EXAM_QUESTION_BY_ID');
export const CREATE_NEW_EXAM_QUESTION = apiTypes('CREATE_NEW_EXAM_QUESTION');
export const DELETE_EXAM_QUESTION = apiTypes('DELETE_EXAM_QUESTION');
export const RESET_STATUS_CREATED_EXAM_QUESTION = "RESET_STATUS_CREATED_EXAM_QUESTION";
export const EDIT_EXAM_QUESTION_INFO = apiTypes('EDIT_EXAM_QUESTION_INFO');
export const GET_EXAM_QUESTION_OF_SYSTEM_FOR_COMPANY = apiTypes('GET_EXAM_QUESTION_OF_SYSTEM_FOR_COMPANY');

//PART MANAGEMENT
export const GET_DETAIL_INFO_PART = apiTypes('GET_DETAIL_INFO_PART');
export const UPLOAD_EXAMPLE_IMAGE_FOR_PART = apiTypes('UPLOAD_EXAMPLE_IMAGE_FOR_PART');
export const DELETE_EXAMPLE_IMAGE = apiTypes('DELETE_EXAMPLE_IMAGE');
export const UPDATE_ANSWER_EXAMPLE = apiTypes('UPDATE_ANSWER_EXAMPLE');
export const UPLOAD_AUDIO_FOR_TEST = apiTypes('UPLOAD_AUDIO_FOR_TEST');

//QUESTIONS
export const UPDATE_QUESTION = apiTypes('UPDATE_QUESTION');
export const UPLOAD_QUESTION_IMAGE = apiTypes('UPLOAD_QUESTION_IMAGE');
export const DELETE_QUESTION_IMAGE = apiTypes('DELETE_QUESTION_IMAGE');
export const UPLOAD_PARAGRAPH_IMAGE = apiTypes('UPLOAD_PARAGRAPH_IMAGE');
export const DELETE_PARAGRAPH_IMAGE = apiTypes('DELETE_PARAGRAPH_IMAGE');
export const CHANGE_STATUS_IS_FIRST_GROUP_QUESTION = "CHANGE_STATUS_IS_FIRST_GROUP_QUESTION";

//EXAM_QUESTION_SCORE
export const GET_ALL_EXAM_QUESTION_SCORE = apiTypes('GET_ALL_EXAM_QUESTION_SCORE');
export const CREATE_EXAM_QUESTION_SCORE = apiTypes('CREATE_EXAM_QUESTION_SCORE');
export const EDIT_EXAM_QUESTION_SCORE = apiTypes('EDIT_EXAM_QUESTION_SCORE');
export const RESET_STATUS_CREATED_EXAM_QUESTION_SCORE = "RESET_STATUS_CREATED_EXAM_QUESTION_SCORE";
export const DELETE_EXAM_QUESTION_SCORE = apiTypes('DELETE_EXAM_QUESTION_SCORE');
export const GET_DETAIL_EXAM_QUESTION_SCORE_BY_ID = apiTypes('GET_DETAIL_EXAM_QUESTION_SCORE_BY_ID');
export const UPDATE_DETAIL_EXAM_QUESTION_SCORE = apiTypes('UPDATE_DETAIL_EXAM_QUESTION_SCORE');
export const IMPORT_SCORE_MAPPING_FILE = apiTypes('IMPORT_SCORE_MAPPING_FILE');

//EXAM_SCHEDULE
export const GET_ALL_EXAM_SCHEDULE = apiTypes('GET_ALL_EXAM_SCHEDULE');
export const UPDATE_STATUS_EXAM_SCHEDULE = apiTypes('UPDATE_STATUS_EXAM_SCHEDULE');
export const GET_EXAM_SCHEDULE_BY_ID = apiTypes('GET_EXAM_SCHEDULE_BY_ID');
export const DELETE_EXAM_SCHEDULE = apiTypes('DELETE_EXAM_SCHEDULE');
export const CREATE_EXAM_SCHEDULE = apiTypes('CREATE_EXAM_SCHEDULE');
export const EDIT_EXAM_SCHEDULE = apiTypes('EDIT_EXAM_SCHEDULE');
export const CHANGE_VIEW_ANSWER_EXAM_STATUS = apiTypes('CHANGE_VIEW_ANSWER_EXAM_STATUS');
export const DELETE_EMAIL_INVITATION = apiTypes('DELETE_EMAIL_INVITATION');
export const IMPORT_FILE_EMAIL_INVITATION = apiTypes('IMPORT_FILE_EMAIL_INVITATION');

//SAMPLE EXAMS
export const GET_ALL_SAMPLE_EXAMS = apiTypes('GET_ALL_SAMPLE_EXAMS');
export const CREATE_SAMPLE_EXAM = apiTypes('CREATE_SAMPLE_EXAM');
export const GET_SAMPLE_EXAM_BY_ID = apiTypes('GET_SAMPLE_EXAM_BY_ID');
export const EDIT_SAMPLE_EXAM = apiTypes('EDIT_SAMPLE_EXAM');
export const DELETE_SAMPLE_EXAM = apiTypes('DELETE_SAMPLE_EXAM');
export const CHANGE_STATUS_SAMPLE_EXAM = apiTypes('CHANGE_STATUS_SAMPLE_EXAM');
export const CHANGE_VIEW_ANSWER_STATUS = apiTypes('CHANGE_VIEW_ANSWER_STATUS');

//REPORTS
export const GET_ALL_REPORT = apiTypes('GET_ALL_REPORT');
export const GET_DETAIL_REPORT_BY_EXAM_ID = apiTypes('GET_DETAIL_REPORT_BY_EXAM_ID');

//CONTACT MANAGEMENT
export const GET_ALL_CONTACTS = apiTypes('GET_ALL_CONTACTS');
export const DELETE_CONTACT = apiTypes('DELETE_CONTACT');
export const CHANGE_CONTACT_STATUS = apiTypes('CHANGE_CONTACT_STATUS');

//SLIDE MANAGEMENT
export const GET_ALL_SLIDE = apiTypes('GET_ALL_SLIDE');
export const ADD_SLIDE = apiTypes('ADD_SLIDE');
export const DELETE_SLIDE = apiTypes('DELETE_SLIDE');
export const CHANGE_SLIDE_STATUS = apiTypes('CHANGE_SLIDE_STATUS');
export const GET_SLIDE_BY_ID = apiTypes('GET_SLIDE_BY_ID');
export const EDIT_SLIDE = apiTypes('EDIT_SLIDE');

//CATEGORY MANAGEMENT
export const GET_ALL_CATEGORY = apiTypes('GET_ALL_CATEGORY');
export const ADD_NEW_CATEGORY = apiTypes('ADD_NEW_CATEGORY');
export const RESET_STATUS_CREATED_CATEGORY = "RESET_STATUS_CREATED_CATEGORY";
export const DELETE_CATEGORY = apiTypes('DELETE_CATEGORY');
export const EDIT_CATEGORY = apiTypes('EDIT_CATEGORY');

//ARTICLES MANAGEMENT
export const GET_ALL_ARTICLES = apiTypes('GET_ALL_ARTICLES');
export const CREATE_NEW_ARTICLE = apiTypes('CREATE_NEW_ARTICLE');
export const DELETE_ARTICLE = apiTypes('DELETE_ARTICLE');
export const CHANGE_ARTICLE_STATUS = apiTypes('CHANGE_ARTICLE_STATUS');
export const GET_ARTICLE_BY_ID = apiTypes('GET_ARTICLE_BY_ID');
export const EDIT_ARTICLE = apiTypes('EDIT_ARTICLE');

//*** CLIENT ***//
//EXAM
export const GET_ALL_EXAM_PRACTICE = apiTypes('GET_ALL_EXAM_PRACTICE');
export const GET_EXAM_BEFORE_TAKEN_BY_ID = apiTypes('GET_EXAM_BEFORE_TAKEN_BY_ID');
export const GET_EXAM_BY_ID_CLIENT = apiTypes('GET_EXAM_BY_ID_CLIENT');
export const SUBMIT_EXAM_ANSWER = apiTypes('SUBMIT_EXAM_ANSWER');
export const GET_RESULT_AFTER_SUBMIT = apiTypes('GET_RESULT_AFTER_SUBMIT');

//SAMPLE
export const GET_SAMPLE_EXAMS_CLIENT = apiTypes('GET_SAMPLE_EXAMS_CLIENT');
export const GET_SAMPLE_EXAM_CLIENT_BEFORE_TAKEN_BY_ID = apiTypes('GET_SAMPLE_EXAM_CLIENT_BEFORE_TAKEN_BY_ID');
export const GET_SAMPLE_EXAM_CLIENT_BY_ID = apiTypes('GET_SAMPLE_EXAM_CLIENT_BY_ID');
export const SUBMIT_SAMPLE_EXAM_ANSWER_CLIENT = apiTypes('SUBMIT_SAMPLE_EXAM_ANSWER_CLIENT');

//CONTACT
export const SEND_CONTACT = apiTypes('SEND_CONTACT');

//MY_REPORTS
export const MY_REPORTS = apiTypes('MY_REPORTS');

//RESULT
export const GET_RESULT_BY_REPORT_ID = apiTypes('GET_RESULT_BY_REPORT_ID');
 
//TIPS
export const GET_ALL_TIPS = apiTypes('GET_ALL_TIPS');
export const GET_DETAIL_TIP = apiTypes('GET_DETAIL_TIP');

//MAIN INFO(in Homepage Admin)
export const GET_ALL_MAIN_INFO = apiTypes('GET_ALL_MAIN_INFO');

//COMPANY
export const GET_ALL_COMPANY = apiTypes('GET_ALL_COMPANY');
export const UPDATE_INFO_COMPANY = apiTypes('UPDATE_INFO_COMPANY');

//HOME_CLIENT
export const GET_INFO_HOME_CLIENT = apiTypes('GET_INFO_HOME_CLIENT');

export const GET_ALL_ARTICLE_CLIENT = apiTypes('GET_ALL_ARTICLE_CLIENT');
export const VIEW_DETAIL_ARTICLE_CLIENT = apiTypes('VIEW_DETAIL_ARTICLE_CLIENT');

//STATISTICALS
export const GET_STATISTICALS = apiTypes('GET_STATISTICALS');
export const GET_DETAIL_STATISTICAL_OF_USER = apiTypes('GET_DETAIL_STATISTICAL_OF_USER');


